
import type { Metadata } from "next";
import { Inter, Crimson_Text } from "next/font/google";
import "./globals.css";
import "./masters.css"
import { myFont } from './fonts';
import LoaderWrapper from "@/components/core/LoaderWrapper";
import Navbar from "@/components/core/Navbar";
import Footer from "@/components/core/Footer";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});


const crimson = Crimson_Text({
  subsets: ["latin"],
  weight: ["400", "600", "700"],
  variable: "--font-crimson",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (
    <html
      lang="en"
      className={`${inter.variable} ${crimson.variable} ${myFont.variable} h-full antialiased`}
    >
      <body className="">
        <Navbar />
        <LoaderWrapper>
          {children}
        </LoaderWrapper>
        <Footer />
      </body>
    </html>
  );
}
